.PHONY: clean All

All:
	@echo "==========Building project:[ testcodelit - Debug ]=========="
	@cd "testcodelit" && "$(MAKE)" -f  "testcodelit.mk"
clean:
	@echo "==========Cleaning project:[ testcodelit - Debug ]----------"
	@cd "testcodelit" && "$(MAKE)" -f  "testcodelit.mk" clean
